# Generated by Django 5.1 on 2024-08-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=500)),
                ("product_image", models.ImageField(default=None, upload_to="images")),
                ("product_overview", models.CharField(max_length=100)),
                ("product_description", models.TextField()),
                ("product_price", models.IntegerField(default=0)),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("In Stock", "In Stock"),
                            ("Out of Stock", "Out of Stock"),
                        ],
                        default="In Stock",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
