# Generated by Django 5.1 on 2024-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], default='In Stock', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_overview',
            field=models.CharField(max_length=100),
        ),
    ]
